FROM apache/airflow:2.9.3-python3.11

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements-runtime.txt /tmp/requirements-runtime.txt

RUN pip install --no-cache-dir -r /tmp/requirements-runtime.txt
